# Generated by Django 3.2.13 on 2023-04-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_recom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('paragraph_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('paragraph_color', models.CharField(max_length=30)),
                ('paragraph_content', models.CharField(max_length=301)),
                ('paragraph_page', models.IntegerField()),
                ('scrap_count', models.IntegerField(blank=True, null=True)),
                ('paragraph_score', models.IntegerField(blank=True, null=True)),
                ('paragraph_score_type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'paragraph',
                'managed': False,
            },
        ),
    ]
