# Generated by Django 4.0 on 2023-03-22 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_isbn', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=128)),
                ('book_publisher', models.CharField(max_length=50)),
                ('book_price', models.IntegerField()),
                ('book_description', models.TextField()),
                ('book_score', models.FloatField(blank=True, null=True)),
                ('book_grade', models.FloatField(blank=True, null=True)),
                ('book_image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookLikes',
            fields=[
                ('book_like_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'book_likes',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('follow_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('followings', models.BigIntegerField()),
                ('followers', models.BigIntegerField()),
            ],
            options={
                'db_table': 'follow',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('hashtag_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hashtag_name', models.TextField()),
                ('hashtag_p_score', models.FloatField()),
                ('hashtag_n_score', models.FloatField()),
            ],
            options={
                'db_table': 'hashtag',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('review_content', models.CharField(blank=True, max_length=255, null=True)),
                ('review_grade', models.FloatField()),
                ('user_id', models.BigIntegerField()),
                ('book_isbn', models.CharField(max_length=32)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('scrap_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('paragraph_id', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scrap',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('email', models.CharField(max_length=64, unique=True)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('nickname', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_type', models.IntegerField(blank=True, null=True)),
                ('user_role', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('prefer_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('user_image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('image_path', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dbmain.user')),
            ],
            options={
                'db_table': 'user_image',
            },
        ),
        migrations.CreateModel(
            name='UserHashtag',
            fields=[
                ('user_hashtag_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dbmain.hashtag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dbmain.user')),
            ],
            options={
                'db_table': 'user_hashtag',
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('paragraph_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('book_isbn', models.CharField(max_length=255)),
                ('paragraph_color', models.CharField(max_length=30)),
                ('paragraph_content', models.CharField(max_length=301)),
                ('paragraph_page', models.IntegerField()),
                ('scrap_count', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dbmain.user')),
            ],
            options={
                'db_table': 'paragraph',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('comment_content', models.CharField(max_length=255)),
                ('comment_depth', models.IntegerField()),
                ('comment_group', models.IntegerField()),
                ('paragraph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbmain.paragraph')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbmain.user')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('book_genre_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_isbn', models.ForeignKey(db_column='book_isbn', on_delete=django.db.models.deletion.CASCADE, related_name='bg_id', to='dbmain.book')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bg_id', to='dbmain.genre')),
            ],
            options={
                'db_table': 'book_genre',
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('book_Author_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ba_id', to='dbmain.author')),
                ('book_isbn', models.ForeignKey(db_column='book_isbn', on_delete=django.db.models.deletion.CASCADE, related_name='ba_id', to='dbmain.book')),
            ],
            options={
                'db_table': 'book_author',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', through='dbmain.BookAuthor', to='dbmain.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books', through='dbmain.BookGenre', to='dbmain.Genre'),
        ),
    ]
