# Generated by Django 4.0 on 2023-03-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(max_length=256),
        ),
    ]
