# Generated by Django 4.1.7 on 2023-03-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_isbn', models.CharField(max_length=13)),
                ('book_image', models.CharField(max_length=300)),
                ('cartoon', models.FloatField(default=0)),
                ('solid', models.FloatField(default=0)),
                ('infographic', models.FloatField(default=0)),
                ('realistic', models.FloatField(default=0)),
                ('art', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'bookinfo',
            },
        ),
    ]
