# Generated by Django 4.0 on 2023-03-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfoModel',
            fields=[
                ('book_isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('book_image', models.CharField(max_length=300)),
                ('anger', models.FloatField(default=0)),
                ('disgust', models.FloatField(default=0)),
                ('fear', models.FloatField(default=0)),
                ('joy', models.FloatField(default=0)),
                ('sadness', models.FloatField(default=0)),
                ('surprise', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'bookinfo',
            },
        ),
    ]
