# Generated by Django 4.0 on 2023-03-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcover', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfomodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookinfomodel',
            name='book_isbn',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
