# Generated by Django 4.0 on 2023-03-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfoModel',
            fields=[
                ('book_isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('book_image', models.CharField(max_length=300)),
                ('feeling', models.IntegerField()),
            ],
            options={
                'db_table': 'bookcover_recommend',
            },
        ),
    ]
